/**:
  ros__parameters:
    # -- Node Configurations --
    waypoints_velocity: 5.0

    # -- A* search Configurations --
    # base configs
    use_back: true
    only_behind_solutions: false
    time_limit: 30000.0
    # robot configs
    maximum_turning_radius: 20.0
    turning_radius_size: 5
    vehicle_dimension_margin: 0.0
    # search configs
    theta_size: 48
    goal_angular_tolerance: 0.05236
    reverse_weight: 2.0
    goal_lateral_tolerance: 0.25
    goal_longitudinal_tolerance: 1.0
    # costmap configs
    obstacle_threshold: 100
    distance_heuristic_weight: 1.0

    # vehicle characteristics for vehicle_constants_manager operation
    # when launching the whole system these parameters should not be part of this package's params
    # however to be able to run the node standalone these parameters are required
    vehicle:
      wheel_radius: 0.37 # Measured from SVL
      wheel_width: 0.27 # Measured from SVL
      wheel_base: 2.734 # Measured from SVL
      wheel_tread: 1.571 # Measured from SVL
      overhang_front: 1.033 # Measured from SVL
      overhang_rear: 1.021 # Measured from SVL
      overhang_left: 0.3135 # Measured from SVL
      overhang_right: 0.3135 # Measured from SVL
      vehicle_height: 1.662 # Measured from SVL
      cg_to_rear: 1.367 # Assuming it is in middle of front and rear axle centers
      tire_cornering_stiffness_front: 0.1 # Taken from AVP demo params, can't verify
      tire_cornering_stiffness_rear: 0.1 # Taken from AVP demo params, can't verify
      mass_vehicle: 2120.0 # Measured from SVL
      inertia_yaw_kg_m2: 12.0  # Taken from AVP demo params, can't verify
      maximum_turning_angle_rad: 0.53
