/**:
  ros__parameters:
    num_anchors: 3
    anchors: [12.0, 16.0, 19.0, 36.0, 40.0, 28.0, 36.0, 75.0, 76.0, 55.0, 72.0, 146.0, 142.0, 110.0, 192.0, 243.0, 459.0, 401.0]
    scale_x_y: [1.2, 1.1, 1.05]
    score_threshold: 0.1
    iou_thresh: 0.45
    detections_per_im: 100
    use_darknet_layer: true
    ignore_thresh: 0.5
