#!/usr/bin/env python

from __future__ import print_function

import argparse
import math
import sys

import numpy as np
import rospy
import tf
from autoware_planning_msgs.msg import StopReasonArray
from geometry_msgs.msg import PoseStamped
from rtree import index

from self_pose_listener import SelfPoseListener
from case_converter import pascal2snake


class StopReason2PoseNode:
    def __init__(self, options):
        self._options = options
        self._tf_broadcaster = tf.TransformBroadcaster()
        self._sub_pose = rospy.Subscriber(
            self._options.topic_name, StopReasonArray, self._on_stop_reasons, queue_size=100
        )
        self._pub_pose_map = {}
        self._idx_map = {}
        self._pose_map = {}
        self._self_pose_listener = SelfPoseListener()

    def _on_stop_reasons(self, msg):
        for stop_reason in msg.stop_reasons:
            snake_case_stop_reason = pascal2snake(stop_reason.reason)

            for stop_factor in stop_reason.stop_factors:
                pose = PoseStamped()
                pose.header = msg.header
                pose.pose = stop_factor.stop_pose

                # Get nearest pose
                th_dist = 1.0
                nearest_pose_id = self._get_nearest_pose_id(snake_case_stop_reason, pose.pose, th_dist)
                if nearest_pose_id:
                    self._update_pose(snake_case_stop_reason, pose.pose, nearest_pose_id)
                    pose_id = nearest_pose_id
                else:
                    pose_id = self._register_pose(snake_case_stop_reason, pose.pose)

                pose_topic_name = "{snake_case_stop_reason}_{pose_id}".format(**locals())
                if pose_topic_name not in self._pub_pose_map:
                    self._pub_pose_map[pose_topic_name] = rospy.Publisher(
                        "~pose/" + pose_topic_name, PoseStamped, queue_size=1
                    )

                self._pub_pose_map[pose_topic_name].publish(pose)

            # Publish nearest stop_reason without number
            self_pose = self._self_pose_listener.get_current_pose()

            nearest_pose = PoseStamped()
            nearest_pose.header = msg.header
            nearest_pose.pose = self._get_nearest_pose_in_array(stop_reason, self_pose.pose)

            if nearest_pose.pose:
                if snake_case_stop_reason not in self._pub_pose_map:
                    self._pub_pose_map[snake_case_stop_reason] = rospy.Publisher(
                        "~pose/" + snake_case_stop_reason, PoseStamped, queue_size=1
                    )
                self._pub_pose_map[snake_case_stop_reason].publish(nearest_pose)

    def _get_nearest_pose_in_array(self, stop_reason, self_pose):
        poses = [stop_factor.stop_pose for stop_factor in stop_reason.stop_factors]
        if not poses:
            return None

        dists = map(lambda p: StopReason2PoseNode.calc_distance2d(p, self_pose), poses)
        nearest_idx = np.argmin(dists)

        return poses[nearest_idx]

    def _find_nearest_pose_id(self, name, pose):
        if name not in self._idx_map:
            self._idx_map[name] = index.Index()

        return self._idx_map[name].nearest(StopReason2PoseNode.pose2boundingbox(pose), 1)

    def _get_nearest_pose_id(self, name, pose, th_dist):
        nearest_pose_ids = list(self._find_nearest_pose_id(name, pose))
        if not nearest_pose_ids:
            return None

        nearest_pose_id = nearest_pose_ids[0]
        nearest_pose = self._get_pose(name, nearest_pose_id)
        if not nearest_pose:
            return None

        dist = StopReason2PoseNode.calc_distance2d(pose, nearest_pose)
        if dist > th_dist:
            return None

        return nearest_pose_id

    def _get_pose(self, name, id):
        if name not in self._pose_map:
            return None

        return self._pose_map[name][id]

    def _update_pose(self, name, pose, id):
        self._pose_map[name][id] = pose
        self._idx_map[name].insert(id, StopReason2PoseNode.pose2boundingbox(pose))

    def _register_pose(self, name, pose):
        if name not in self._pose_map:
            self._pose_map[name] = {}

        id = len(self._pose_map[name]) + 1
        self._pose_map[name][id] = pose
        self._idx_map[name].insert(id, StopReason2PoseNode.pose2boundingbox(pose))
        return id

    @staticmethod
    def calc_distance2d(pose1, pose2):
        p1 = pose1.position
        p2 = pose2.position
        return math.hypot(p1.x - p2.x, p1.y - p2.y)

    @staticmethod
    def pose2boundingbox(pose):
        return [pose.position.x, pose.position.y, pose.position.x, pose.position.y]


def main(args):
    rospy.init_node("stop_reason2pose")

    parser = argparse.ArgumentParser()
    parser.add_argument("topic_name", type=str)
    ns = parser.parse_args(args)

    StopReason2PoseNode(ns)
    rospy.spin()


if __name__ == "__main__":
    main(sys.argv[1:])
