#!/usr/bin/env bash

stop_reason_name=$1

if [ -z "${stop_reason_name}" ]; then
  echo "Please input stop_reason_name as the 1st argument."
  exit 1
fi

rosrun autoware_debug_tools stop_reason2pose /planning/scenario_planning/status/stop_reasons >/dev/null 2>&1 &
rosrun autoware_debug_tools pose2tf /stop_reason2pose/pose/${stop_reason_name} ${stop_reason_name} >/dev/null 2>&1 &
rosrun autoware_debug_tools tf2pose ${stop_reason_name} base_link 100 >/dev/null 2>&1 &
rosrun tf tf_echo ${stop_reason_name} base_link 100 2>/dev/null

wait
