# Node
update_rate: 10
visualize_lanelet: false

# Core
footprint_margin: 0.0
resample_interval: 0.3
max_deceleartion: 2.8
delay_time: 1.3
max_lateral_deviation: 2.0
max_longitudinal_deviation: 2.0
max_yaw_deviation_deg: 60.0
