/**:
  ros__parameters:
    frame_id: base_link
    twist_covariance:
      [
        0.04,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        10000.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        10000.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        10000.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        10000.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.01,
      ]
