/**:
  ros__parameters:
    planning:
      type: diagnostic_aggregator/AnalyzerGroup
      path: planning
      analyzers:
        alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": planning_topic_status"]
              timeout: 1.0
              num_items: 0
