/**:
  ros__parameters:
    update_rate: 10.0
    diag_config:
      name: "speaker"
      hardware_id: "speaker"
      msg_ok: ""
      msg_warn: "speaker is unstable"
      msg_error: "speaker is broken"
      msg_stale: ""
